configuration_files :
    - ".flake8"
    - ".isort.cfg"
    - ".pre-commit-config.yaml"
    - ".pylintrc"
repository: https://raw.githubusercontent.com/Pierre-Sassoulas/centralized-pre-commit-conf
branch: master
path: "centralized_pre_commit_conf/static"
dependencies: ["black==19.3b0", "isort==4.3.15", "pylint", "flake8"]
gitignore_info_text: "# Configuration file added automatically by 'centralized-pre-commit-conf'"
update_gitignore: False
replace_existing: False
verbose: False
insecure: False
